Update template to use new capa and remove capo
giantswarm/gitops-template pull request #102
Opened 2024-10-10 13:05 UTC by pipo02mix

Part of https://github.com/giantswarm/giantswarm/issues/30971

2024-10-11 12:13 UTC, mproffitt commented on docs/add_mc.md
> +      name: ${MC_NAME}-GitOps
Prefer lowercase in code

```suggestion
      name: ${MC_NAME}-gitops
```

2024-10-11 12:14 UTC, mproffitt commented on docs/add_org.md
> +gonna use `LastPass` for that:
```suggestion
going to use `LastPass` for that:
```

Prefer clean English over slang

2024-10-11 12:15 UTC, mproffitt commented on management-clusters/MC_NAME/MC_NAME.yaml
> +  name: mc-name-GitOps  # TODO: change "mc-name" to your Management Cluster name
```suggestion
  name: mc-name-gitops  # TODO: change "mc-name" to your Management Cluster name
```

2024-10-11 12:22 UTC, mproffitt commented on tests/ats/assertions/exists/organizations/workload-clusters/capi-wc-name/app_capi-wc-name.yaml
> +  version: 2.2.0
I think this is now an empty string as version comes from release version

2024-10-11 12:33 UTC, mproffitt requested changes
I think I found all of them ...

2024-10-11 12:33 UTC, mproffitt commented on tests/ats/assertions/exists/organizations/workload-clusters/hello-app-staging-1/apps.yaml
> +  version: 2.2.0
I think here too - can be an empty string. This would lead to confusion for customers wondering what version to put in there when in fact it's ignored.

2024-10-11 12:33 UTC, mproffitt commented on tests/ats/conftest.py
> +        self.GitOps_repo_url = os.environ[self._GITOPS_REPO_URL_ENV_VAR_NAME]
```suggestion
        self.gitops_repo_url = os.environ[self._GITOPS_REPO_URL_ENV_VAR_NAME]
```

2024-10-11 12:33 UTC, mproffitt commented on tests/ats/conftest.py
> +        if not validators.url(self.GitOps_repo_url):
```suggestion
        if not validators.url(self.gitops_repo_url):
```

2024-10-11 12:33 UTC, mproffitt commented on tests/ats/conftest.py
> +                f" [current value: '{self.GitOps_repo_url}']."
```suggestion
                f" [current value: '{self.gitops_repo_url}']."
```

2024-10-11 12:33 UTC, mproffitt commented on tests/ats/conftest.py
> +        self.GitOps_repo_branch = os.environ[self._GITOPS_REPO_BRANCH_ENV_VAR_NAME]
```suggestion
        self.gitops_repo_branch = os.environ[self._GITOPS_REPO_BRANCH_ENV_VAR_NAME]
```

2024-10-11 12:33 UTC, mproffitt commented on tests/ats/conftest.py
> +                f"in the GitOps repository configured by '{self.GitOps_repo_url}'"
```suggestion
                f"in the GitOps repository configured by '{self.gitops_repo_url}'"
```

2024-10-11 15:13 UTC, pipo02mix commented on tests/ats/assertions/exists/organizations/workload-clusters/capi-wc-name/app_capi-wc-name.yaml
> +  version: 2.2.0
ok good point let me leave it empty

2024-10-25 13:41 UTC, mproffitt approved these changes
LGTM

2024-10-25 13:41 UTC, merged