Add missing step in the MC template
giantswarm/gitops-template pull request #17
Opened 2022-04-20 13:54 UTC by pipo02mix

2022-04-20 13:54 UTC, pipo02mix commented on docs/add_mc.md
> +2. Create the MC kustomization file poiting the git repo and applied it:
```suggestion
2. Create the MC kustomization file pointing to the git repo and apply it:
```

2022-04-20 14:05 UTC, MarcelMue reviewed
@ljakimczuk Can you double check here?

2022-04-20 14:05 UTC, MarcelMue commented on docs/add_mc.md
> +2. Create the MC kustomization file pointing to the git repo and apply it:
```suggestion
1. Create the MC kustomization file pointing to the git repo and apply it:
```

2022-04-20 15:53 UTC, ljakimczuk requested changes

2022-04-20 15:53 UTC, ljakimczuk commented on docs/add_mc.md
> +1. Create the MC kustomization file pointing to the git repo and apply it:
```suggestion
1. Apply the cluster's Kustomization CR:

```sh
kubectl apply -f management-clusters/${MC_NAME}/${MC_NAME}.yaml
```

2022-04-20 15:54 UTC, ljakimczuk commented on docs/add_mc.md
> +1. Create the MC kustomization file pointing to the git repo and apply it:
we do not need to create this Kustomization CR since it leaves in the repository now, we just need to apply it

2022-04-21 12:38 UTC, MarcelMue approved these changes

2022-04-21 13:40 UTC, merged